# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(972, 610)
        self.main_v_layout = QtWidgets.QVBoxLayout(Form)
        self.main_v_layout.setContentsMargins(16, 40, 16, 40)
        self.main_v_layout.setObjectName("main_v_layout")
        self.label_game_difficulty = QtWidgets.QLabel(Form)
        self.label_game_difficulty.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_game_difficulty.setAlignment(QtCore.Qt.AlignCenter)
        self.label_game_difficulty.setObjectName("label_game_difficulty")
        self.main_v_layout.addWidget(self.label_game_difficulty)
        self.progress_bar = QtWidgets.QProgressBar(Form)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.main_v_layout.addWidget(self.progress_bar)
        self.question_h_layout = QtWidgets.QHBoxLayout()
        self.question_h_layout.setSpacing(16)
        self.question_h_layout.setObjectName("question_h_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.question_h_layout.addItem(spacerItem)
        self.labelFirstNumber = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelFirstNumber.setFont(font)
        self.labelFirstNumber.setObjectName("labelFirstNumber")
        self.question_h_layout.addWidget(self.labelFirstNumber)
        self.labelOperation = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelOperation.setFont(font)
        self.labelOperation.setObjectName("labelOperation")
        self.question_h_layout.addWidget(self.labelOperation)
        self.labelSecondNumber = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelSecondNumber.setFont(font)
        self.labelSecondNumber.setObjectName("labelSecondNumber")
        self.question_h_layout.addWidget(self.labelSecondNumber)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.question_h_layout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.question_h_layout.addItem(spacerItem1)
        self.question_h_layout.setStretch(0, 1)
        self.question_h_layout.setStretch(5, 1)
        self.main_v_layout.addLayout(self.question_h_layout)
        self.answers_g_layout = QtWidgets.QGridLayout()
        self.answers_g_layout.setSpacing(40)
        self.answers_g_layout.setObjectName("answers_g_layout")
        self.btn_answer2 = QtWidgets.QPushButton(Form)
        self.btn_answer2.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_answer2.setObjectName("btn_answer2")
        self.answers_g_layout.addWidget(self.btn_answer2, 1, 1, 1, 1)
        self.btn_answer4 = QtWidgets.QPushButton(Form)
        self.btn_answer4.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_answer4.setObjectName("btn_answer4")
        self.answers_g_layout.addWidget(self.btn_answer4, 1, 2, 1, 1)
        self.btn_answer1 = QtWidgets.QPushButton(Form)
        self.btn_answer1.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_answer1.setObjectName("btn_answer1")
        self.answers_g_layout.addWidget(self.btn_answer1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.answers_g_layout.addItem(spacerItem2, 0, 3, 1, 1)
        self.btn_answer3 = QtWidgets.QPushButton(Form)
        self.btn_answer3.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_answer3.setObjectName("btn_answer3")
        self.answers_g_layout.addWidget(self.btn_answer3, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.answers_g_layout.addItem(spacerItem3, 0, 0, 1, 1)
        self.main_v_layout.addLayout(self.answers_g_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_game_difficulty.setText(_translate("Form", "gameDifficulty"))
        self.labelFirstNumber.setText(_translate("Form", "firstNumber"))
        self.labelOperation.setText(_translate("Form", "operation"))
        self.labelSecondNumber.setText(_translate("Form", "secondNumber"))
        self.label.setText(_translate("Form", "= ?"))
        self.btn_answer2.setText(_translate("Form", "PushButton"))
        self.btn_answer4.setText(_translate("Form", "PushButton"))
        self.btn_answer1.setText(_translate("Form", "PushButton"))
        self.btn_answer3.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
